import React from 'react';
import { X, FileText, Download, ShieldCheck, Calendar, MapPin } from 'lucide-react';

export default function ReportsModal({ isOpen, onClose, selectedEvent }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-xs font-poppins">
      <div className="bg-white rounded-2xl border border-slate-200 max-w-2xl w-full p-6 shadow-2xl space-y-4 animate-in fade-in zoom-in duration-150">
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div className="flex items-center space-x-2 text-slate-800">
            <div className="p-2 rounded-xl bg-blue-50 text-blue-600 border border-blue-200">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">Spatial Disaster Risk Report</h3>
              <p className="text-xs text-slate-500">Automated National Flood Prediction &amp; Inundation Summary</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-xl hover:bg-slate-100 text-slate-400 hover:text-slate-700 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-3 text-xs text-slate-700 leading-relaxed">
          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
            <div className="flex items-center justify-between font-semibold text-slate-900">
              <span>Event: {selectedEvent?.name || 'National Flood Forecast'}</span>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-blue-50 text-blue-700 border border-blue-200">
                {selectedEvent?.state || 'India'}
              </span>
            </div>
            <div className="text-[11px] text-slate-500">
              Analysis Date Range: {selectedEvent?.start_date || '2024-06-26'} to {selectedEvent?.end_date || '2024-07-03'}
            </div>
            <p className="text-xs text-slate-600">
              Spatial risk modeling predicts rapid hydro-climatic discharge along the primary river network with low-elevation depressions at critical inundation probability ($&gt;80\%$).
            </p>
          </div>

          <div className="grid grid-cols-2 gap-3 text-xs">
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-100">
              <div className="text-slate-400 text-[10px] uppercase font-bold">Total Estimated Affected Area</div>
              <div className="text-base font-bold text-slate-900 mt-0.5">3,420 km²</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-100">
              <div className="text-slate-400 text-[10px] uppercase font-bold">Early Warning Lead Time</div>
              <div className="text-base font-bold text-emerald-600 mt-0.5">4.5 Days Advance</div>
            </div>
          </div>
        </div>

        <div className="pt-3 border-t border-slate-100 flex items-center justify-between">
          <span className="text-[11px] text-slate-400">Generated by FloodCast AI &bull; Survey of India Sovereign Standards</span>
          <button
            onClick={() => window.print()}
            className="inline-flex items-center space-x-1.5 px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-md shadow-blue-500/20 transition-all cursor-pointer"
          >
            <Download className="w-4 h-4" />
            <span>Export PDF Report</span>
          </button>
        </div>
      </div>
    </div>
  );
}
